[package]
name = "dart_chromaprint"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
base64 = "0.22.1"
flutter_rust_bridge = "=2.11.1"
rubato = "0.16.2"
rustfft = "6.4.1"
rusty-chromaprint = "0.3.0"
symphonia = { version = "0.5.5", features = ["all"] }

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(frb_expand)'] }
