// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `apply_chroma_filter`, `compute_chroma`, `compute_fft_spectrum`, `flush_preprocess_buffer`, `freq_to_index`, `freq_to_octave`, `get_fingerprint_words`, `index_to_freq`, `make_hamming_window`, `normalize_chroma_vectors`, `preprocess_pcm_samples`, `read_pcm_i16`

String greet({required String name}) =>
    RustLib.instance.api.crateApiSimpleGreet(name: name);

Float32List getAudioPcm({required String path, double? maxSeconds}) => RustLib
    .instance
    .api
    .crateApiSimpleGetAudioPcm(path: path, maxSeconds: maxSeconds);

Future<String> getFingerprintRaw({
  required String path,
  required int sampleRate,
  required int channels,
}) => RustLib.instance.api.crateApiSimpleGetFingerprintRaw(
  path: path,
  sampleRate: sampleRate,
  channels: channels,
);

Future<String> getFingerprintRawFromPcm({
  required List<int> samples,
  required int sampleRate,
  required int channels,
}) => RustLib.instance.api.crateApiSimpleGetFingerprintRawFromPcm(
  samples: samples,
  sampleRate: sampleRate,
  channels: channels,
);

Uint32List getFingerprintWordsBaseline({
  required String path,
  required int sampleRate,
  required int channels,
}) => RustLib.instance.api.crateApiSimpleGetFingerprintWordsBaseline(
  path: path,
  sampleRate: sampleRate,
  channels: channels,
);

Uint32List getFingerprintWordsFromPcm({
  required List<int> samples,
  required int sampleRate,
  required int channels,
}) => RustLib.instance.api.crateApiSimpleGetFingerprintWordsFromPcm(
  samples: samples,
  sampleRate: sampleRate,
  channels: channels,
);

Float64List getProcessedPcm({
  required String path,
  required int sampleRate,
  required int channels,
}) => RustLib.instance.api.crateApiSimpleGetProcessedPcm(
  path: path,
  sampleRate: sampleRate,
  channels: channels,
);

Float64List getFftSpectrumBaseline({
  required String path,
  required int sampleRate,
  required int channels,
}) => RustLib.instance.api.crateApiSimpleGetFftSpectrumBaseline(
  path: path,
  sampleRate: sampleRate,
  channels: channels,
);

Float64List getChromaBaseline({
  required String path,
  required int sampleRate,
  required int channels,
}) => RustLib.instance.api.crateApiSimpleGetChromaBaseline(
  path: path,
  sampleRate: sampleRate,
  channels: channels,
);

Float64List getFilteredChromaBaseline({
  required String path,
  required int sampleRate,
  required int channels,
}) => RustLib.instance.api.crateApiSimpleGetFilteredChromaBaseline(
  path: path,
  sampleRate: sampleRate,
  channels: channels,
);

Float64List getNormalizedChromaBaseline({
  required String path,
  required int sampleRate,
  required int channels,
}) => RustLib.instance.api.crateApiSimpleGetNormalizedChromaBaseline(
  path: path,
  sampleRate: sampleRate,
  channels: channels,
);
